{% set name = "bulwark" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 18a61b1f7bb5af6495551a4381e9f511d6c4daf09c168e00f88a81d7f8bb143f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3.6
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - pandas
    - numpy

test:
  imports:
    - bulwark

about:
  home: https://github.com/zaxr/bulwark
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: A python package for defensive data analysis
  description: |
    Bulwark is a package for convenient property-based testing of pandas
    dataframes, supported for Python 3.5+.
  doc_url: https://bulwark.readthedocs.io/
  dev_url: https://github.com/zaxr/bulwark

extra:
  recipe-maintainers:
    - ZaxR
    - jamesmyatt
