{% set name = "bulwark" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1a8b1deb72fe6493f6ecbef2e69bd2f6ba0651c263dd5ab41adbd382cfe0099b

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python >=3.5
  host:
    - python >=3.5
    - pip
    - setuptools
  run:
    - python >=3.5
    - pandas
    - numpy

test:
  imports:
    - bulwark

about:
  home: https://github.com/zaxr/bulwark
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: A python package for defensive data analysis
  description: |
    Bulwark is a package for convenient property-based testing of pandas
    dataframes, supported for Python 3.5+.
  doc_url: https://bulwark.readthedocs.io/
  dev_url: https://github.com/zaxr/bulwark

extra:
  recipe-maintainers:
    - ZaxR
    - jamesmyatt
